name: Upload Images to S3

on:
  push:
    branches:
      - main

jobs:
  lint-test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Image Tools
        run: sudo apt-get install -y imagemagick

      - name: Lint - Check image sizes
        run: |
          for img in $(find ./images -type f -name "*.png"); do
            size=$(identify -format "%wx%h" "$img")
            echo "Image: $img, Size: $size"
          done

      - name: Test - Validate image format
        run: |
          for img in $(find ./images -type f); do
            filetype=$(file --mime-type -b "$img")
            echo "$img is of type $filetype"
            if [[ "$filetype" != image/* ]]; then
              echo "❌ Invalid image format: $img"
              exit 1
            fi
          done

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: my-image-assets
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'images'
